<button class="btn-xyz$id $class" id="$id">$children</button>

<style>
  .btn-xyz$id{
    padding: $padding;
    border: solid 2px #00C896;
    color: white;
    background: var(--accent-color);
    margin: 3px;
    border-radius: var(--lg-radius);
    font-family: "Montserrat";
    font-weight: 600;
    &:hover{
      background: var(--hover-accent-color);
      scale: 0.9;    
    }
  }
</style>
