<header>
  $children
</header>

<style>
  header {
    padding: 20vw 0 50px 0;
    box-sizing: border-box;
    display: flex;
    flex-direction: column;
    align-items: center;
    height: 100vh;
    h1 {
      font-size: clamp(3rem, 5vw, 5rem);
      margin-bottom: 20px;
    }
    
    p {
      max-width: 450px;
      text-align: center;
      margin-bottom: 40px;
    }
    
    button{
      margin: 40px 0;
    }
  }
</style>
